apiVersion: 1

datasources:
  - name: InfluxDB_Ruido
    uid: influxdb_ruido
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iot_proyecto
      defaultBucket: ruido_ambiental
      tlsSkipVerify: true
    secureJsonData:
      token: mi-token-super-secreto-12345
    isDefault: true